include:
  - path: "vpn-server/docker-compose.yaml"
  - path: "proxy-server/docker-compose.yaml"
  - path: "dns-server/docker-compose.yaml"
  - path: "media-server/docker-compose.yaml"
  - path: "password-manager/docker-compose.yaml"
  - path: "cloud-server/docker-compose.yaml"
  - path: "hub/docker-compose.yaml"
  - path: "uptime-monitoring-service/docker-compose.yaml"
