services:
  vpn:
    image: tailscale/tailscale
    container_name: vpn
    restart: always
    hostname: vpn-reverse-proxy
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
      - 81:81
      - 443:443
      - 5335:5335
    volumes:
      - ./tailscale/data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      interval: 15s
      timeout: 3s
      retries: 5

  reverse-proxy:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: reverse-proxy
    restart: always
    depends_on:
      - vpn
    network_mode: service:vpn
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/lets-encrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
      retries: 5
