services:
  vpn:
    image: tailscale/tailscale
    container_name: vpn
    restart: unless-stopped
    hostname: media-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
      - 81:81
      - 443:443
      - ${UNBOUND_PORT}:${UNBOUND_PORT}
      - ${JELLYSEERR_PORT}:${JELLYSEERR_PORT}
      - ${JELLYFIN_PORT}:${JELLYFIN_PORT}
    volumes:
      - ./tailscale/data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      interval: 15s
      timeout: 3s
      retries: 5
